# Lock down dist to ensure that builds run on a distribution that supports oraclejdk8
dist: trusty

language: ruby
jdk:
- oraclejdk8
before_install:
- |
  if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    OS=darwin
  else
    sysctl kernel.unprivileged_userns_clone=1
    OS=linux
  fi
  BAZEL_VERSION=$(cat ".bazelversion")
  wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-${OS}-x86_64.sh"
  chmod +x install.sh
  ./install.sh --user
  rm -f install.sh
before_script:
- echo "startup --output_base=$HOME/.cache/bazel" >> .bazelrc
# Avoid progress indicators that can blow out log which makes using WEB UI difficult
- echo "common --noshow_progress" >> .bazelrc
- echo "common --noshow_loading_progress" >> .bazelrc
# This is so we understand failures better
- echo "build --verbose_failures" >> .bazelrc
script: bazel build :all
git:
  depth: false
