repositories:
  remote:
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/staging
   - https://stocksoftware.jfrog.io/stocksoftware/maven2

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.17

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1
  jetbrains_annotations: org.realityforge.org.jetbrains.annotations:org.jetbrains.annotations:jar:1.7.0

  # GWT deps
  gwt_user: com.google.gwt:gwt-user:jar:2.9.0
  gwt_dev: com.google.gwt:gwt-dev:jar:2.9.0

  jsinterop_annotations: com.google.jsinterop:jsinterop-annotations:jar:2.0.0

  jsinterop_base: com.google.jsinterop:base:jar:1.0.0

  akasha: org.realityforge.akasha:akasha-gwt:jar:0.29

  grim_annotations: org.realityforge.grim:grim-annotations:jar:0.06

  braincheck: org.realityforge.braincheck:braincheck-core:jar:1.31.0

  zemeckis: org.realityforge.zemeckis:zemeckis-core:jar:0.13

  arez_core: org.realityforge.arez:arez-core:jar:0.203
  arez_processor: org.realityforge.arez:arez-processor:jar:0.203
  arez_spytools: org.realityforge.arez:arez-extras-spytools:jar:0.203

  react4j_core: org.realityforge.react4j:react4j-core:jar:0.188
  react4j_dom: org.realityforge.react4j:react4j-dom:jar:0.188
  react4j_processor: org.realityforge.react4j:react4j-processor:jar:0.188

  dagger_core: com.google.dagger:dagger:jar:2.25.2
  dagger_core_sources: com.google.dagger:dagger:jar:sources:2.25.2
  dagger_gwt: com.google.dagger:dagger-gwt:jar:2.25.2
  dagger_producers: com.google.dagger:dagger-producers:jar:2.25.2
  dagger_spi: com.google.dagger:dagger-spi:jar:2.25.2
  dagger_compiler: com.google.dagger:dagger-compiler:jar:2.25.2
  googlejavaformat: com.google.googlejavaformat:google-java-format:jar:1.5
  errorprone: com.google.errorprone:javac-shaded:jar:9-dev-r4023-3
  guava_failureaccess: com.google.guava:failureaccess:jar:1.0.1
  kotlinx_metadata_jvm: org.jetbrains.kotlinx:kotlinx-metadata-jvm:jar:0.1.0
  kotlin_stdlib: org.jetbrains.kotlin:kotlin-stdlib:jar:1.3.50
  kotlin_stdlib_common: org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.3.50
  javapoet: com.squareup:javapoet:jar:1.13.0
  guava: com.google.guava:guava:jar:27.1-jre

  javax_inject: javax.inject:javax.inject:jar:1
  javax_inject_sources: javax.inject:javax.inject:jar:sources:1
