repositories:
  remote:
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/staging
   - https://stocksoftware.jfrog.io/stocksoftware/maven2

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.17

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1
  jetbrains_annotations: org.realityforge.org.jetbrains.annotations:org.jetbrains.annotations:jar:1.7.0

  # GWT deps
  gwt_user: com.google.gwt:gwt-user:jar:2.9.0
  gwt_dev: com.google.gwt:gwt-dev:jar:2.9.0

  jsinterop_annotations: com.google.jsinterop:jsinterop-annotations:jar:2.0.0

  jsinterop_base: com.google.jsinterop:base:jar:1.0.0

  akasha: org.realityforge.akasha:akasha-gwt:jar:0.24

  grim_annotations: org.realityforge.grim:grim-annotations:jar:0.05

  braincheck: org.realityforge.braincheck:braincheck-core:jar:1.31.0

  zemeckis: org.realityforge.zemeckis:zemeckis-core:jar:0.11

  arez_core: org.realityforge.arez:arez-core:jar:0.199
  arez_processor: org.realityforge.arez:arez-processor:jar:0.199
  arez_spytools: org.realityforge.arez:arez-extras-spytools:jar:0.199

  react4j_core: org.realityforge.react4j:react4j-core:jar:0.184
  react4j_dom: org.realityforge.react4j:react4j-dom:jar:0.184
  react4j_processor: org.realityforge.react4j:react4j-processor:jar:0.184

  sting_core: org.realityforge.sting:sting-core:jar:0.20
  sting_processor: org.realityforge.sting:sting-processor:jar:0.20
