repositories:
  remote:
   - http://repo1.maven.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/public
   - https://stocksoftware.jfrog.io/stocksoftware/oss

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.12

  anodoc: org.realityforge.anodoc:anodoc:jar:1.0.0

  javax_jsr305: com.google.code.findbugs:jsr305:jar:3.0.1
  jetbrains_annotations: org.jetbrains:annotations:jar:15.0

  # GWT deps
  gwt_user: com.google.gwt:gwt-user:jar:2.8.2
  gwt_dev: com.google.gwt:gwt-dev:jar:2.8.2

  jsinterop_annotations: com.google.jsinterop:jsinterop-annotations:jar:1.0.2
  jsinterop_annotations_sources: com.google.jsinterop:jsinterop-annotations:jar:sources:1.0.2

  jsinterop_base: com.google.jsinterop:base:jar:1.0.0-beta-3
  jsinterop_base_sources: com.google.jsinterop:base:jar:sources:1.0.0-beta-3

  elemental2_core: com.google.elemental2:elemental2-core:jar:1.0.0-beta-3
  elemental2_dom: com.google.elemental2:elemental2-dom:jar:1.0.0-beta-3
  elemental2_promise: com.google.elemental2:elemental2-promise:jar:1.0.0-beta-3

  react4j_annotation: org.realityforge.react4j:react4j-annotations:jar:0.24
  react4j_core: org.realityforge.react4j:react4j-core:jar:0.24
  react4j_dom: org.realityforge.react4j:react4j-dom:jar:0.24
  react4j_processor: org.realityforge.react4j:react4j-processor:jar:0.24
  react4j_arez: org.realityforge.react4j:react4j-arez:jar:0.24

  arez_annotations: org.realityforge.arez:arez-annotations:jar:gwt:0.35
  arez_core: org.realityforge.arez:arez-core:jar:gwt:0.35
  arez_processor: org.realityforge.arez:arez-processor:jar:0.35
  arez_component: org.realityforge.arez:arez-component:jar:gwt:0.35
  arez_extras: org.realityforge.arez:arez-extras:jar:gwt:0.35
  arez_browser_extras: org.realityforge.arez:arez-browser-extras:jar:gwt:0.35

  braincheck: org.realityforge.braincheck:braincheck:jar:gwt:1.3.0
